<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <#include "style.ftlh">
    <title>${name} dn42 Automatic Peering</title>
</head>
<body class="markdown-body">
<h1>${name} dn42 Peering</h1>
<p><b>Already a peer? <a href="/manage">Login</a>.</b></p>
<h2>Peering Process</h2>
<ol>
    <li>You: Register and verify your ASN.</li>
    <li>You: Add a peer and submit your info.</li>
    <li>We: Validate your info automatically.</li>
    <li>We: If nothing goes wrong, we will automatically connect your endpoint.</li>
    <li>You: Update your configuration to peer with us.</li>
    <li>We: Constantly check your connection.</li>
    <li>If you decided to stop peering with us, just login and delete your connection. We will stop connecting with you. The whole process is automated.</li>
</ol>
<h2>Start peering today!</h2>
<ol>
    <li>Register your ASN <a href="/asn">Here</a>.</li>
    <li>Login to your <a href="/manage">Management Portal</a>.</li>
    <li>Start peering by <a href="/manage/new">Creating a Peer</a>.</li>
</ol>
</body>
</html>
