name: Publish

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_central:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Generate tag
        run: echo "CUSTOM_DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build and push central Docker image
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          tags: $CUSTOM_DOCKER_TAG
  build_agent: 
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: ./gradlew :agent:distTar
      - uses: ncipollo/release-action@v1.7.3
        with:
          allowUpdates: true
          artifacts: "./agent/build/distributions/agent-*.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
