name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build_central:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate tag
        run: echo "CUSTOM_BUILD=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew -Pbuild_ver=$CUSTOM_BUILD :central:distTar
      - uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: "./central/build/distributions/central-*.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
  build_agent: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate tag
        run: echo "CUSTOM_BUILD=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew -Pbuild_ver=$CUSTOM_BUILD :agent:distTar
      - uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: "./agent/build/distributions/agent-*.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
